## Import Libraries

In [2]:
from pathlib import Path
import pandas as pd

## Define Project Path

In [3]:
PROJECT_ROOT = Path.cwd().parent
PROJECT_ROOT

WindowsPath('e:/Projects/restaurant-powerbi-dashboard/restaurant-powerbi-dashboard')

## Load the Restaurant Dataset

In [4]:
excel_path = PROJECT_ROOT / "data" / "Restaurant.xlsx"
excel_path

WindowsPath('e:/Projects/restaurant-powerbi-dashboard/restaurant-powerbi-dashboard/data/Restaurant.xlsx')

In [5]:
excel_file = pd.ExcelFile(excel_path)
excel_file.sheet_names

['Dishes',
 'Events',
 'EventsLocations',
 'Orders',
 'OrdersDishes',
 'CustomersEvents',
 'CustomersDishes',
 'Customers',
 'Reservations']

## Inspect Customers Table

In [6]:
customers = pd.read_excel(excel_path, sheet_name="Customers")
customers.head()

,CustomerID,FirstName,LastName,Email,Address,City,State,Phone,Birthday,FavoriteDish
0,1,Maggi,Domney,mdomney0@wisdompets.com,53177 Fieldstone Pass,San Bernardino,CA,760-702-5469,1938-10-11,15
1,2,Javier,Dawks,jdawks1@red30design.com,25629 Brown Trail,Hartford,CT,860-906-1459,1953-11-21,13
2,3,Aleen,Fasey,afasey2@kinetecoinc.com,41967 Mockingbird Court,Boca Raton,FL,561-410-2222,1900-08-10,3
3,4,Taylor,Jenkins,tjenkins@rouxacademy.org,968 Bartillon Park,Fort Lauderdale,FL,954-294-7424,1961-05-02,8
4,5,Imogen,Kabsch,ikabsch@landonhotel.com,222 Hudson Point,Anderson,SC,864-326-7456,1919-08-27,17

In [7]:
customers.shape

(100, 10)

In [8]:
customers.columns

Index(['CustomerID', 'FirstName', 'LastName', 'Email', 'Address', 'City',
       'State', 'Phone', 'Birthday', 'FavoriteDish'],
      dtype='str')

### Check Data Types

In [9]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    100 non-null    int64
 1   FirstName     100 non-null    str
 2   LastName      100 non-null    str
 3   Email         100 non-null    str
 4   Address       100 non-null    str
 5   City          100 non-null    str
 6   State         100 non-null    str
 7   Phone         100 non-null    str
 8   Birthday      100 non-null    datetime64[us]
 9   FavoriteDish  100 non-null    int64
dtypes: datetime64[us](1), int64(2), str(7)
memory usage: 7.9 KB

### Check Missing Values

In [10]:
customers.isnull().sum()

CustomerID      0
FirstName       0
LastName        0
Email           0
Address         0
City            0
State           0
Phone           0
Birthday        0
FavoriteDish    0
dtype: int64

### Check Duplicates

In [11]:
customers.duplicated().sum()

np.int64(0)

### Check Customer ID Uniqueness
If "true" then CustomerID can safely act as the primary key of the Customers table.

In [15]:
customers["CustomerID"].is_unique

# another method to check, both are correct
# customers["CustomerID"].duplicated().sum()

True

## Inspect Dishes Table

In [16]:
dishes = pd.read_excel(excel_path, sheet_name="Dishes")
dishes.head()

,DishID,Name,Description,Price
0,1,Parmesan Deviled Eggs,These delectable little bites are made with or...,8.0
1,2,Artichokes with Garlic Aioli,Our artichokes are brushed with an olive oil a...,9.0
2,3,French Onion Soup,Caramelized onions slow cooked in a savory bro...,7.0
3,4,Mini Cheeseburgers,These mini cheeseburgers are served on a fresh...,8.0
4,5,Panko Stuffed Mushrooms,Large mushroom caps are filled a savory cream ...,7.0

In [17]:
dishes.shape

(22, 4)

In [18]:
dishes.columns

Index(['DishID', 'Name', 'Description', 'Price'], dtype='str')

### Check Dishes Data Quality

In [19]:
dishes.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DishID       22 non-null     int64
 1   Name         22 non-null     str
 2   Description  22 non-null     str
 3   Price        22 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 836.0 bytes

In [20]:
dishes.isnull().sum()

DishID         0
Name           0
Description    0
Price          0
dtype: int64

In [21]:
dishes.duplicated().sum()

np.int64(0)

In [22]:
dishes["DishID"].is_unique

True

### One extra useful check here
Because Price is important for revenue analysis we can quickly see whether the prices look reasonable.
This gives us:
- minimum price
- maximum price
- average price
- quartiles

In [23]:
dishes["Price"].describe()

count    22.000000
mean      8.042273
std       1.860381
min       4.000000
25%       7.000000
50%       8.500000
75%       9.990000
max       9.990000
Name: Price, dtype: float64

## Inspect Orders Table

In [24]:
orders = pd.read_excel(excel_path, sheet_name="Orders")
orders.head()

   OrderID  CustomerID           OrderDate
0        1          17 2019-02-01 17:32:00
1        2          17 2019-02-02 16:52:00
2        3           2 2019-02-02 16:53:00
3        4          45 2019-02-02 16:58:00
4        5          86 2019-02-03 12:04:00

In [25]:
orders.shape

(10, 3)

In [26]:
orders.columns

Index(['OrderID', 'CustomerID', 'OrderDate'], dtype='str')

### Check Orders Data Quality

In [27]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     10 non-null     int64
 1   CustomerID  10 non-null     int64
 2   OrderDate   10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(2)
memory usage: 372.0 bytes

In [28]:
orders.isnull().sum()

OrderID       0
CustomerID    0
OrderDate     0
dtype: int64

In [29]:
orders.duplicated().sum()

np.int64(0)

In [30]:
orders["OrderID"].is_unique

True

### Validate Customer IDs in Orders
We want to verify that every CustomerID used in Orders actually exists in the Customers table.

In [31]:
orders["CustomerID"].isin(customers["CustomerID"]).all()

np.True_

## Inspect OrdersDishes Table

In [32]:
orders_dishes = pd.read_excel(excel_path, sheet_name="OrdersDishes")
orders_dishes.head()

   OrdersDishesID  OrderID  DishID
0               1        1      12
1               2        2       5
2               3        2       9
3               4        3       7
4               5        3      10

In [33]:
orders_dishes.shape

(20, 3)

In [34]:
orders_dishes.columns

Index(['OrdersDishesID', 'OrderID', 'DishID'], dtype='str')

## Inspect Remaining Tables

In [36]:
remaining_sheets = [
    "Reservations",
    "Events",
    "EventsLocations",
    "CustomersEvents",
    "CustomersDishes"
]

summary = []

for sheet in remaining_sheets: # Repeat the code once for each sheet name.
    df = pd.read_excel(excel_path, sheet_name=sheet) # Loads the current sheet.

    summary.append({
        "Table": sheet,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "MissingValues": df.isnull().sum().sum(),
        "DuplicateRows": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary) # Show it as table.
summary_df

             Table  Rows  Columns  MissingValues  DuplicateRows
0     Reservations    13        4              0              0
1           Events    15        5              0              0
2  EventsLocations     5        3              0              0
3  CustomersEvents    10        3              0              0
4  CustomersDishes     8        3              0              0